# Generated by Django 6.0.5 on 2026-05-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='our_brands',
            name='Description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
