# Generated by Django 6.0.5 on 2026-05-14 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_our_brands_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='Media/images/category'),
        ),
        migrations.AlterField(
            model_name='featured_categories',
            name='image',
            field=models.ImageField(upload_to='Media/images/featured'),
        ),
        migrations.AlterField(
            model_name='our_brands',
            name='image',
            field=models.ImageField(upload_to='Media/images/brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='Media/images/product'),
        ),
        migrations.AlterField(
            model_name='product_flag',
            name='image',
            field=models.ImageField(upload_to='Media/images/product_flag'),
        ),
    ]
